In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("w_review_train.csv", delimiter=";", quotechar='"', names=['review', 'rating'])

In [3]:
data = data[:10000]

In [4]:
from sklearn.metrics import f1_score
import numpy as np
y_pred = np.zeros(len(data))
data2 = np.zeros(len(data))
data4 = np.array([data2, data2, data2, data2])
data4

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [5]:
for i in range(len(data)):
    data4[0][i] = data.loc[i][0].count('ไม่อร่อย')
    data4[1][i] = data.loc[i][0].count('แย่')
    data4[2][i] = data.loc[i][0].count('คุ้ม')
    data4[1][i] = data.loc[i][0].count('มาอีก')

In [6]:
y_true = data['rating']

In [7]:
data4 = data4.T
data4

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
y_true = np.array(y_true)
y_true

array([3, 4, 3, ..., 5, 2, 5])

In [9]:
model = LinearRegression()
normalized_X_Train = preprocessing.normalize(data4)
standardized_X_Train = preprocessing.scale(normalized_X_Train)

model.fit(data4, y_true)

predictions = model.predict(data4)
normalized_X_Train

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
# predictions = predictions.astype(int)
for i in range(len(predictions)):
    if predictions[i] - int(predictions[i]) < 0.5:
        predictions[i] = int(predictions[i])
    else:
        predictions[i] = int(predictions[i]) + 1
predictions

array([ 4.,  4.,  4., ...,  4.,  3.,  4.])

In [11]:
f1_score(y_true, predictions, average='macro')

/home/ekapolc/.env/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.15177738647361211